In [1]:
import numpy as np

In [2]:
# Steps to move north /south /east /west
dx=[1,0,-1,0]
dy=[0,1,0,-1]

In [3]:
# Check if the cell is inside the matrix boundaries
def inside(x,y) :
    return ((x>=0) and (y>=0) and (x<n) and (y<n))

In [4]:
# Depth First Search traversal
def explore_dfs(matrix,x,y) :
    visited[x][y] = counter
    result = 1
    for k in range(4) :
        nx = x + dx[k]
        ny = y+dy[k]
        # if new cell is inside the matrix boundries and has the same value, we continue exploring through it
        if(inside(x,y) and inside(nx,ny) and (matrix[nx][ny]==matrix[x][y]) and ( visited[nx][ny] == 0)):
            result= explore_dfs(matrix,nx,ny) + result
    return result

In [5]:
n = int(input('enter size of matrix '))

enter size of matrix 10


In [6]:
import numpy as np
matrix = np.random.choice([x for x in range(0, 5)], n*n)
matrix.resize(n, n)
matrix = matrix.astype(int)

In [7]:
visited = np.zeros((n,n))
visited = visited.astype(int)

In [8]:
best = 0
bi = 0
bj = 0
counter = 0

In [9]:
for i in range(n):
    for j in range(n):
        if (visited[i][j] == 0):
            counter =counter + 1            
            curr = explore_dfs(matrix,i,j)
            if (curr > best) :
                best = curr
                bi=i
                bj=j

In [10]:
print(matrix)
print('\n')
print('The largest island contains {} values \n'.format(best))
for i in range(n):
    for j in range(n):
        if (visited[i][j] == visited[bi][bj]) :
            print("X ", end='')
        else :
            print(". ", end='')
    print('\n')

[[2 1 2 0 3 0 1 0 3 1]
 [3 2 3 2 2 1 3 0 2 2]
 [2 4 1 2 0 1 2 4 1 2]
 [4 4 2 1 1 0 3 1 1 2]
 [0 4 1 4 2 3 0 4 2 0]
 [0 4 3 1 4 1 3 2 1 1]
 [4 4 4 4 4 3 0 4 2 3]
 [1 4 3 3 1 4 1 4 4 3]
 [3 4 0 1 4 0 4 4 4 3]
 [0 0 3 4 0 0 2 4 3 1]]


The largest island contains 13 values 

. . . . . . . . . . 

. . . . . . . . . . 

. X . . . . . . . . 

X X . . . . . . . . 

. X . . . . . . . . 

. X . . X . . . . . 

X X X X X . . . . . 

. X . . . . . . . . 

. X . . . . . . . . 

. . . . . . . . . . 

