In [16]:
import sys
import numpy as np

In [17]:
dx = [1,0,-1,0]
dy = [0,1,0,-1]

In [25]:
def display_path(matrix,path) :
    print('Path that sums up to 21 \n')
    for elt in path :
        x,y = elt
        print (matrix[x][y], ' (', x, ',', y,')')
    print('\n')
    sys.exit(1)


In [26]:
def inside(x,y) :
    return ((x>=0) and (y>=0) and (x<n) and (y<n))

In [27]:
def value(matrix,path) :
    result = 0
    for elt in path:
        x,y = elt
        result += matrix[x][y]
    return result

In [28]:
def explore_dfs(matrix,i,j,curr,length) :
    if (value(matrix,curr)>21):
        return
    if(value(matrix,curr)==21) :
        if(curr.__len__() == length):
            display_path(matrix,curr)
        else :
            return
    for k in range(4) :
        ni = i + dx[k]
        nj = j + dy[k]
        if (not inside(ni,nj)) or ((ni,nj) in curr):
            continue
        tmp = curr[:]
        tmp.append((i,j))
        explore_dfs(matrix,ni, nj, tmp, length)        
        

In [29]:
n = int(input('enter size of matrix: '))

enter size of matrix: 5


In [30]:
matrix = np.random.randint(10, size=(n, n))
print(matrix)

[[3 0 3 6 4]
 [4 2 7 1 0]
 [9 4 9 4 6]
 [3 9 1 0 4]
 [8 9 2 5 1]]


In [31]:
for length in range(3,22):
    for i in range(n):
        for j in range(n) :
            tmp = []
            explore_dfs(matrix,i, j, tmp, length)


Path that sums up to 21 

9  ( 2 , 0 )
3  ( 3 , 0 )
9  ( 3 , 1 )




SystemExit: 1

C:\Users\hamar\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2971: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
