In [1]:
import sys
import numpy as np

In [2]:
# Steps to move north /south /east /west
dx = [1,0,-1,0]
dy = [0,1,0,-1]

In [3]:
# Print the path
def display_path(matrix,path) :
    print('Path that sums up to 21 \n')
    for elt in path :
        x,y = elt
        print (matrix[x][y], ' (', x, ',', y,')')
    print('\n')
    sys.exit(1)


In [4]:
# Check if the cell is inside the matrix boundaries
def inside(x,y) :
    return ((x>=0) and (y>=0) and (x<n) and (y<n))

In [5]:
# Count the sum of values in the matrix
def value(matrix,path) :
    result = 0
    for elt in path:
        x,y = elt
        result += matrix[x][y]
    return result

In [6]:
# Depth First Search traversal
def explore_dfs(matrix,i,j,curr) :
    if (value(matrix,curr)>21):
        return
    if(value(matrix,curr)==21) :
        display_path(matrix,curr)
        return
    for k in range(4) :
        ni = i + dx[k]
        nj = j + dy[k]
        if (inside(ni,nj) == 0) or ((ni,nj) in curr):
            # if a new cell is out of boundaries or already in path we skip it
            continue
        tmp = curr[:]
        tmp.append((i,j))
        # we continue exploring through the new cell
        explore_dfs(matrix,ni, nj, tmp)
            

In [7]:
n = int(input('enter size of matrix :'))
print('\n')
matrix = np.random.randint(10, size=(n, n))
print(matrix)

enter size of matrix :10


[[6 9 4 9 8 7 0 7 0 0]
 [0 4 8 9 9 9 7 0 2 7]
 [1 6 4 0 5 4 7 2 2 8]
 [7 4 0 4 0 9 0 9 4 8]
 [5 7 9 2 5 2 4 6 2 9]
 [8 4 3 7 6 7 2 6 3 2]
 [2 9 7 2 9 6 5 9 2 6]
 [9 4 0 8 4 4 6 9 0 7]
 [4 3 0 0 2 6 8 1 9 0]
 [5 5 9 9 8 4 2 6 6 0]]


In [8]:
for i in range(n):
    for j in range(n) :
        tmp = []
        explore_dfs(matrix,i,j,tmp)        
        

Path that sums up to 21 

6  ( 0 , 0 )
0  ( 1 , 0 )
1  ( 2 , 0 )
6  ( 2 , 1 )
4  ( 3 , 1 )
0  ( 3 , 2 )
4  ( 3 , 3 )




SystemExit: 1

C:\Users\hamar\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2971: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
