In [1]:
import sys
import numpy as np

In [2]:
dx = [1,0,-1,0]
dy = [0,1,0,-1]

In [17]:
def display_path(matrix,path) :
    print('Path that sums up to 21 \n')
    for elt in path :
        x,y = elt
        print (matrix[x][y], ' (', x, ',', y,')')
    print('\n')
    sys.exit(1)


In [18]:
def inside(x,y) :
    return ((x>=0) and (y>=0) and (x<n) and (y<n))

In [19]:
def value(matrix,path) :
    result = 0
    for elt in path:
        x,y = elt
        result += matrix[x][y]
    return result

In [20]:
def explore_dfs(matrix,i,j,curr) :
    if (value(matrix,curr)>21):
        return
    if(value(matrix,curr)==21) :
        display_path(matrix,curr)
        return
    for k in range(4) :
        ni = i + dx[k]
        nj = j + dy[k]
        if (not inside(ni,nj)) or ((ni,nj) in curr):
            continue
        tmp = curr[:]
        tmp.append((i,j))
        explore_dfs(matrix,ni, nj, tmp)
        
        

In [31]:
n = int(input('enter size of matrix :'))
print('\n')
matrix = np.random.randint(10, size=(n, n))
print(matrix)

enter size of matrix :6


[[1 9 5 5 0 8]
 [2 9 9 3 9 9]
 [8 5 0 8 2 1]
 [0 9 4 5 2 0]
 [0 1 1 9 4 9]
 [5 0 6 2 6 5]]


In [32]:
for i in range(n):
    for j in range(n) :
        tmp = []
        explore_dfs(matrix,i,j,tmp)        
        

Path that sums up to 21 

1  ( 0 , 0 )
2  ( 1 , 0 )
8  ( 2 , 0 )
0  ( 3 , 0 )
0  ( 4 , 0 )
1  ( 4 , 1 )
1  ( 4 , 2 )
6  ( 5 , 2 )
2  ( 5 , 3 )




SystemExit: 1

C:\Users\hamar\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2971: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
